name: Firmware bug report
description: Create a bug report related with firmware
title: ''
labels: ["Type: Bug","Status: Waiting triage"]
assignees: ''
body:
  - type: markdown
     attributes:
      value: Please read the following information before posting the issue. Whenever it's clear that the below content was not read and follower, the issue is likely to be closed with "please read the template". Don't take offense at this. It is simply a time management decision. Whenever an issue is raised without following the template and the required information is not provided, very often too much time is then spent going back and forth to obtain details that are outlined below.

  - type: markdown
     attributes:
      value: |
        # **Before posting the issue**

        If you have a **question**, need clarification on something, need help on a particular situation or want to start a discussion, **DO NOT** open an issue here. _It will be automatically closed!_ 
        
        Ask the question on one of our [Discord channels](https://discordapp.com/invite/gCyBu8T), making sure to select the channel that's most appropriate to the context so subject matter experts are most likely to answer promptly. 
        If you're not keen to Discord, you can also use [GitHub Discussions](https://github.com/nanoframework/Home/discussions) in this same repo.
        Or, alternatively, on [Stack Overflow](https://stackoverflow.com/questions/tagged/nanoframework) using the `nanoframework` tag. 

  - type: input
    id: target
    attributes:
      label: Target
      description: What's the name of target where you're seeing this happening. If applicable.
      placeholder: ex. ST_STM32F769I_DISCOVERY, ESP_WROVER_KIT, ALL
    validations:
      required: false

  - type: input
    id: fw_version
    attributes:
      label: Firmware version
      description: What's the firmware version where you're seeing this happening. If applicable.
      placeholder: ex. 1.2.3.456, N/A
    validations:
      required: false

  - type: input
    id: working_before
    attributes:
      label: Was working before? On which version?
      description: If you knew this was working before, let us know on which version.
      placeholder: ex. 1.2.3.456, N/A
    validations:
      required: false

  - type: textarea
    id: dev_caps
    attributes:
      label: Device capabilities
      description: Device Capabilites output (if relevant)
      placeholder: You can grab this from Device Explorer in Visual Studio
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: How to reproduce
      description: Detailed repro steps so we can see the same problem.
      value: |
        1.
        2.
        ...
    validations:
      required: false

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Very helpful if you send along a few screenshots to help visualize the issue!
      placeholder: if applicable/relevant
    validations:
      required: false

  - type: textarea
    id: other_things
    attributes:
      label: Aditional information
      description: Other suggested things.
      placeholder: |
        if applicable/relevant
        for example link to the repository with sample code
        code snippets
    validations:
      required: false

  - type: markdown
     attributes:
      value: |
        ### Make an effort to fix the bug
        
        Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.
