name: Bug report for libraries, IoT bindings or API
description: Create a bug report related with one of the libraries, BCL, API, IoT bindings or NuGet packages
labels: 
  - "Type: Bug"
  - "Status: Waiting triage"
body:
  - type: markdown
    attributes:
      value: |
        # :warning: **Please read before raising the issue** :warning:

        If you have a **question**, need clarification on something, need help on a particular situation or want to start a discussion, **DO NOT** open an issue here. _It will be automatically closed!_ 
        
        Ask the question on one of our [Discord channels](https://discordapp.com/invite/gCyBu8T), making sure to select the channel that's most appropriate to the context so subject matter experts are most likely to answer promptly. 
        If you're not keen to Discord, you can also use [GitHub Discussions](https://github.com/nanoframework/Home/discussions) in this same repo.
        Or, alternatively, on [Stack Overflow](https://stackoverflow.com/questions/tagged/nanoframework) using the `nanoframework` tag. 

        If you realy want to raise an issue, please make sure to follow the template and provide the required information. Failing to do so will most likely end up on the issue being close. Don't take offense at this. It is simply a time management decision. Whenever an issue is raised without following the template and the required information is not provided, very often too much time has to be spent going back and forth to obtain the details that are outlined below.

  - type: input
    id: library
    attributes:
      label: Library/API/IoT binding
      description: The name of the .NET nanoFramework library, binding or NuGet package.
      placeholder: name of the library
    validations:
      required: true

  - type: input
    id: vs_version
    attributes:
      label: Visual Studio version
      description: Version of Visual Studio. If applicable.
      placeholder: ex. VS2019 (16.10) or VS2022 (17.1)
    validations:
      required: false

  - type: input
    id: extension_version
    attributes:
      label: .NET nanoFramework extension version
      description: Version of .NET nanoFramework extension for Visual Studio. If applicable.
      placeholder: ex. 2019.1.2.3 or 2022.7.8.9
    validations:
      required: false

  - type: input
    id: target
    attributes:
      label: Target name(s)
      description: What's the name(s) of target(s) where you're seeing this happening. If applicable.
      placeholder: ex. ST_STM32F769I_DISCOVERY, ESP_WROVER_KIT, ALL
    validations:
      required: false

  - type: input
    id: fw_version
    attributes:
      label: Firmware version
      description: What's the firmware version where you're seeing this happening. If applicable.
      placeholder: ex. 1.2.3.456, N/A
    validations:
      required: false

  - type: textarea
    id: dev_caps
    attributes:
      label: Device capabilities
      description: Device Capabilites output. If relevant.
      placeholder: You can grab this from Device Explorer in Visual Studio
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: How to reproduce
      description: Detailed repro steps so we can see the same problem. If not already explained above.
      placeholder: |
        1.
        2.
        ...
    validations:
      required: false

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen. If applicable.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Very helpful if you send along a few screenshots to help visualize the issue!
      placeholder: drag and drop here, if applicable
    validations:
      required: false

  - type: textarea
    id: sample_project
    attributes:
      label: Sample project or code
      description: Sample project that reproduces the problem. If applicable.
      placeholder: |
        Paste here an URL for a github repo with a project reproducing the problem
        Or copy & paste here a a code snnipet that reproduces the problem
        You can also add a link to a sample code in https://dotnetfiddle.net/ if you need to show a comparison with the full .NET
    validations:
      required: false

  - type: textarea
    id: other_things
    attributes:
      label: Aditional information
      description: Other suggested things. If applicable/relevant.
      placeholder: |
        for example link to the repository with sample code
        code snippets
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Make an effort to fix the bug
        
        Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.
